M48
; DRILL file {KiCad (6.0.7-1)-1} date Thursday, 13 October 2022 at 17:45:32
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-13T17:45:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.25Y-3.42
X3.3Y-1.52
X5.3Y-2.12
X5.3Y-3.22
T0
M30
